theme: jekyll-theme-minimal
title: IuK-Backend
description: Ein einfaches Einsatz Management Werkzeug
show_downloads: "true"
logo: "logo_.svg"
githubProjectServerURL: ""
githubProjectServerName: ""
githubProjectServerWinURL: ""
githubProjectServerMacURL: ""
githubProjectServerLnxURL: ""