theme: jekyll-theme-minimal
title: IuK-Backend
description: IuK-Backend digitale Unterstützung für IuK Gruppen.
show_downloads: "true"
logo: "/logo.png"
lang: "de_DE"
githubProjectServerURL: "https://github.com/iuk-backend/iuk-backend-server"
githubProjectServerWinURL: "https://github.com/iuk-backend/iuk-backend-server/releases/latest/download/iuk-backend-server-windows.zip"
githubProjectServerMacURL: "https://github.com/iuk-backend/iuk-backend-server/releases/latest/download/iuk-backend-server-macos.zip"
githubProjectServerLnxURL: "https://github.com/iuk-backend/iuk-backend-server/releases/latest/download/iuk-backend-server-linux.zip"